<?php



/**
 * Implements hook_menu_alter().
 */
function fblogin_helper_menu_alter(&$items) {
  //Allow visitors to register using fb access, but prevent usage of the page against manual registration.  This will work if allow visitors to register is enable in the account settings
  $items['user/register']['access callback'] = FALSE;
  $items['user/password']['access callback'] = FALSE;
}


/**
 * Implements hook_user_presave().
 */
function fblogin_helper_user_presave(&$edit, $account, $category) {
  if((!isset($edit['fboauth']) || !$edit['fboauth']) && $account->is_new){
    drupal_access_denied();
    drupal_set_message(t('You can only register via Facebook'), 'error', TRUE);
    drupal_exit();
  }
}


/**
 * Implements hook_user_presave().
 */
function fblogin_helper_fboauth_user_presave(&$edit, $fbuser) {
  if(!array_key_exists('pass', $edit)){
    $pass = _fblogin_helper_genpass();
    $edit['pass'] = $pass;
  }
}

function _fblogin_helper_genpass(){
  $pass = '';
  $length = 8;
  $allowable_characters = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!#$%&()*+,-./:;<=>?@[]^_{|}~';

  // Zero-based count of characters in the allowable list:
  $len = strlen($allowable_characters) - 1;

  // Loop the number of times specified by $length.
  for ($i = 0; $i < $length; $i++) {
    // Each iteration, pick a random character from the
    // allowable string and append it to the password:
    $pass .= $allowable_characters[mt_rand(0, $len)];
  }

  return $pass;
}

/**
 * Implements hook_page_alter().
 */
function fblogin_helper_page_alter(&$page) {
  //sets the views block as an available variable in tpl file
  $block = block_load('views', '4b693386ec754134225cbb56853b8f9c');
  $block = _block_get_renderable_array(_block_render_blocks(array($block)));
  $block = drupal_render($block);
  $page['search_block'] = $block;

  //render facebook login moudle block
  $block = block_load('fboauth', 'login');
  $block = _block_get_renderable_array(_block_render_blocks(array($block)));
  $block = drupal_render($block);
  $page['fb_block'] = $block;
}

function fblogin_helper_fboauth_action__connect($variables) {
  $action = $variables['action'];
  $link = $variables['properties'];
  $url = url($link['href'], array('query' => $link['query']));
  $link['attributes']['class'][] = 'facebook-action-connect';
  $link['attributes']['rel'] = 'nofollow';
  $attributes = isset($link['attributes']) ? drupal_attributes($link['attributes']) : '';
  $title = isset($link['title']) ? check_plain($link['title']) : '';
  $src = ($GLOBALS['is_https'] ? 'https' : 'http') . '://www.facebook.com/images/fbconnect/login-buttons/connect_light_medium_short.gif';
  return '<span>Log in/Sign up&nbsp;</span><a ' . $attributes . ' href="' . $url . '"><img src="' . $src . '" alt="' . $title . '" /></a>';
}

/**
 * Implements hook_form_alter().
 */
function fblogin_helper_form_alter(&$form, &$form_state, $form_id) {
  if($form_id ==  'user_profile_form'){
    $form['account']['name']['#disabled'] = TRUE;
    $form['account']['pass']['#disabled'] = TRUE;
    $form['account']['current_pass']['#disabled'] = TRUE;
    $form['account']['current_pass_required_values']['#disabled'] = TRUE;
    $form['account']['mail']['#disabled'] = TRUE;
  }
}